# Generated by Django 6.0 on 2026-06-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_about_user_education_info_user_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diploma_file',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
    ]
